//
// Generated by CocoaPods-Keys
// on 02/08/2023
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

NS_ASSUME_NONNULL_BEGIN

@interface WebSDKKeys : NSObject

@property (readonly) NSString *appIdSTG;
@property (readonly) NSString *appKeySTG;
@property (readonly) NSString *appVerSTG;
@property (readonly) NSString *secretKeySTG;
@property (readonly) NSString *appIdProd;
@property (readonly) NSString *appKeyProd;
@property (readonly) NSString *appVerProd;
@property (readonly) NSString *secretKeyProd;

@end

NS_ASSUME_NONNULL_END
